#include <cs50.h>
#include <ctype.h>
#include <math.h>
#include <stdio.h>
#include <string.h>

int count_letters(string text);
int count_words(string text);
int count_sentences(string text);

int main(void)
{
    // Prompt the user for some text
    string text = get_string("Text: ");

    // Count the number of letters, words, and sentences in the text
    int letters = count_letters(text);
    int words = count_words(text);
    int sentences = count_sentences(text);

    // Calculate the average number of letters per 100 words in the text
    float L = ((float) letters / words) * 100;

    // Calculate the average number of sentences per 100 words in the text
    float S = ((float) sentences / words) * 100;

    // Compute the Coleman-Liau index
    int index = round(0.0588 * L - 0.296 * S - 15.8);

    // Print the grade level
    if (index >= 16)
    {
        printf("Grade 16+\n");
    }
    else if (index < 1)
    {
        printf("Before Grade 1\n");
    }
    else
    {
        printf("Grade %i\n", index);
    }
}

int count_letters(string text)
{
    // Return the number of letters in text
    int letters = 0;
    for (int i = 0, len = strlen(text); i < len; i++)
    {
        if (isalpha(text[i]))
        {
            letters++;
        }
    }
    return letters;
}

int count_words(string text)
{
    // Return the number of words in text
    // A sentence always starts with a word before there's space.
    int words = 1;
    for (int i = 0, len = strlen(text); i < len; i++)
    {
        if (isspace(text[i]))
        {
            words++;
        }
    }
    return words;
}

int count_sentences(string text)
{
    // Return the number of sentences in text
    int sentences = 0;
    for (int i = 0, len = strlen(text); i < len; i++)
    {
        if ((text[i]) == '.' || (text[i]) == '!' || (text[i]) == '?')
        {
            sentences++;
        }
    }
    return sentences;
}

/*
Terminal Output
readability/ $ ./readability
Text: A large class of computational problems involve the determination of properties of graphs, digraphs, integers, arrays of integers, finite families of finite sets, boolean formulas and elements of other countable domains.
Grade 16+
readability/ $ ./readability
Text: One fish. Two fish. Red fish. Blue fish.
Before Grade 1
readability/ $ check50 cs50/problems/2026/x/readability
Connecting.........
Authenticating....
Verifying.......
Preparing.....
Uploading........
Waiting for results.......................
Results for cs50/problems/2026/x/readability generated by check50 v4.0.0.dev0
:) readability.c exists
:) readability.c compiles
:) handles single sentence with multiple words
:) handles punctuation within a single sentence
:) handles more complex single sentence
:) handles multiple sentences
:) handles multiple more complex sentences
:) handles longer passages
:) handles multiple sentences with different punctuation
:) handles questions in passage
:) handles reading level before Grade 1
:) handles reading level at Grade 16+
To see more detailed results go to https://submit.cs50.io/check50/603953d5f807081f446931628d74fd9537e652cd
readability/ $ 
*/