#include <cs50.h>
#include <ctype.h>
#include <stdio.h>
#include <string.h>

// Points assigned to each letter of the alphabet
int POINTS[] = {1, 3, 3, 2, 1, 4, 2, 4, 1, 8, 5, 1, 3, 1, 1, 3, 10, 1, 1, 1, 1, 4, 4, 8, 4, 10};

int compute_score(string word);

int main(void)
{
    // Prompt the user for two words
    string word_1 = get_string("Player 1: ");
    string word_2 = get_string("Player 2: ");

    // Compute the score of each word
    int score_1 = compute_score(word_1);
    int score_2 = compute_score(word_2);

    // Print the winner
    if (score_1 > score_2)
    {
        printf("Player 1 wins!\n");
    }
    else if (score_1 < score_2)
    {
        printf("Player 2 wins!\n");
    }
    else
    {
        printf("Tie!\n");
    }
}

int compute_score(string word)
{
    // Keep track of score
    int score = 0;

    // Compute score for each character
    for (int i = 0, len = strlen(word); i < len; i++)
    {
        if (isupper(word[i]))
        {
            score += POINTS[word[i] - 'A'];
        }
        else if (islower(word[i]))
        {
            score += POINTS[word[i] - 'a'];
        }
    }
    return score;
}

/*
Terminal Output
$ cd scrabble
scrabble/ $ ./scrabble
Player 1: Question?
Player 2: Question!
Tie!
scrabble/ $ ./scrabble
Player 1: red
Player 2: wheelbarrow
Player 2 wins!
scrabble/ $ ./scrabble
Player 1: COMPUTER
Player 2: science
Player 1 wins!
scrabble/ $ ./scrabble
Player 1: Scrabble
Player 2: wiNNeR
Player 1 wins!
scrabble/ $ 
scrabble/ $ 
scrabble/ $ check50 cs50/problems/2026/x/scrabble
Connecting........
Authenticating....
Verifying.........
Preparing.....
Uploading........
Waiting for results...................................
Results for cs50/problems/2026/x/scrabble generated by check50 v4.0.0.dev0
:) scrabble.c exists
:) scrabble.c compiles
:) handles letter cases correctly
:) handles punctuation correctly
:) correctly identifies 'Question?' and 'Question!' as a tie
:) correctly identifies 'drawing' and 'illustration' as a tie
:) correctly identifies 'hai!' as winner over 'Oh,'
:) correctly identifies 'COMPUTER' as winner over 'science'
:) correctly identifies 'Scrabble' as winner over 'wiNNeR'
:) correctly identifies 'pig' as winner over 'dog'
:) correctly identifies 'Skating!' as winner over 'figure?'
:) correctly identifies winner between random words
:) implementation correctly calculates scores using the Scrabble points table
*/