// This program encrypts a message by shifting each letter by a specified number of positions.
// The 'key' is provided as a command-line argument in the terminal

#include <cs50.h>
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

bool only_digits(string s);
char rotate(char c, int n);

int main(int argc, string argv[])
{
    // Make sure the program was run with just one command-line argument
    // if the number of arguments in main() != 2, print a warning: "Usage: ./caesar key\n"
    // The program only accepts 2 agruments './caesar' and the 'key'
    if (argc != 2)
    {
        printf("Usage: ./caesar key\n");
        return 1;
    }

    // Make sure every character in arg[v] is a digit
    if (!only_digits(argv[1]))
    {
        printf("Usage: ./caesar key\n");
        return 1;
    }
    // Convert argv[1] from a 'string' to an 'int'
    int n = (atoi(argv[1]));

    // Prompt user for plaintext
    string text = get_string("plaintext: ");

    // Print ciphertext
    printf("ciphertext: ");

    // For each character in plaintext
    // Rotate the character if it's a letter
    for (int i = 0, len = strlen(text); i < len; i++)
    {
        printf("%c", rotate(text[i], n));
    }
    printf("\n");

    // Return 0 to indicate successful execution
    return 0;
}

bool only_digits(string s)
{
    // Make sure every character in arg[v] is a digit
    for (int i = 0, len = strlen(s); i < len; i++)
    {
        if (!isdigit(s[i]))
        {
            return false;
        }
    }
    return true;
}

char rotate(char c, int n)
{
    // Encipher each plaintext character
    if (!isalpha(c))
    {
        return c;
    }
    else if (isupper(c))
    {
        // Convert letter to a 0-25 ASCII index, add the key
        // Use % 26 to wrap around from 'Z' back to 'A'
        return (c - 'A' + n) % 26 + 'A';
    }
    else
    {
        // Convert letter to a 0-25 ASCII index, add the key
        // Use % 26 to wrap around from 'z' back to 'a'
        return (c - 'a' + n) % 26 + 'a';
    }
}

/*
Terminal Output:
$ cd caesar
caesar/ $ make caesar
caesar/ $ style50 caesar.c
caesar/ $ make caesar
caesar/ $ ./caesar 42
plaintext: Hello
ciphertext: Xubbe
caesar/ $ ./caesar 1233774543
plaintext: Shin234TAO##$$was
ciphertext: Tijo234UBP##$$xbt
caesar/ $ ./caesar er34
Usage: ./caesar key
caesar/ $ ./caesar
Usage: ./caesar key
caesar/ $ ./caesar 123
plaintext: caeSAR123!
ciphertext: vtxLTK123!
caesar/ $ check50 cs50/problems/2026/x/caesar
Waiting for results.............................
Results for cs50/problems/2026/x/caesar generated by check50 v4.0.0.dev0
:) caesar.c exists.
:) caesar.c compiles.
:) encrypts "a" as "b" using 1 as key
:) encrypts "barfoo" as "yxocll" using 23 as key
:) encrypts "BARFOO" as "EDUIRR" using 3 as key
:) encrypts "BaRFoo" as "FeVJss" using 4 as key
:) encrypts "barfoo" as "onesbb" using 65 as key
:) encrypts "world, say hello!" as "iadxp, emk tqxxa!" using 12 as key
:) handles lack of argv[1]
:) handles non-numeric key
:) handles too many arguments

*/