// This program determines and prints the winner(s) of an election
// The winner is the candidate or candidates who receives the highest number of votes

#include <cs50.h>
#include <stdio.h>
#include <string.h>

// Max number of candidates
#define MAX 9

// Candidates have name and vote count
typedef struct
{
    string name;
    int votes;
} candidate;

// Array of candidates
candidate candidates[MAX];

// Number of candidates
int candidate_count;

// Function prototypes
bool vote(string name);
void print_winner(void);
int get_max_votes(candidate list[MAX], int count);

int main(int argc, string argv[])
{
    // Check for invalid usage
    if (argc < 2)
    {
        printf("Usage: plurality [candidate ...]\n");
        return 1;
    }

    // Populate array of candidates
    candidate_count = argc - 1;
    if (candidate_count > MAX)
    {
        printf("Maximum number of candidates is %i\n", MAX);
        return 2;
    }
    for (int i = 0; i < candidate_count; i++)
    {
        candidates[i].name = argv[i + 1];
        candidates[i].votes = 0;
    }

    int voter_count = get_int("Number of voters: ");

    // Loop over all voters
    for (int i = 0; i < voter_count; i++)
    {
        string name = get_string("Vote: ");

        // Check for invalid vote
        if (!vote(name))
        {
            printf("Invalid vote.\n");
        }
    }

    // Display winner of election
    print_winner();
}

// Update vote totals given a new vote
bool vote(string name)
{
    // Iterate over each candidate
    for (int i = 0; i < candidate_count; i++)
    {
        // Check if candidate's name matches given name
        if (strcmp(candidates[i].name, name) == 0)
        // If yes, increment candidate's votes and return true
        {
            candidates[i].votes += 1;
            return true;
        }
    }
    // If no match, return false
    return false;
}

// Print the winner (or winners) of the election
void print_winner(void)
{
    // Find the maximum number of votes
    int max_votes = get_max_votes(candidates, candidate_count);

    // Print heading (removed for cs50 compatability)
    // printf("Candidate(s) with the most votes:\n");

    // Print the candidate (or candidates) with maximum votes
    for (int i = 0; i < candidate_count; i++)
    {
        if (candidates[i].votes == max_votes)
        {
            printf("%s\n", candidates[i].name);
        }
    }
    return;
}

// Get the highest number of votes overall
int get_max_votes(candidate list[MAX], int count)
{
    int max_votes = 0;
    // Loop over each candidate to determine the highest vote count
    for (int i = 0; i < count; i++)
    {
        if (list[i].votes > max_votes)
        {
            max_votes = list[i].votes;
        }
    }
    return max_votes;
}


/*
Terminal Output
$ cd plurality
plurality/ $ make plurality
plurality/ $ ./plurality Alice Bob Mike
Number of voters: 7
Vote: Alice
Vote: Bob
Vote: Bob
Vote: Jon
Invalid vote.
Vote: Bob
Vote: Mike
Vote: Mike
Candidate(s) with the most votes:
Bob
plurality/ $ ./plurality Alice Bob Mike
Number of voters: 7
Vote: Alice
Vote: Alice
Vote: Bob
Vote: Bob
Vote: Okon
Invalid vote.
Vote: Mike
Vote: Jon
Invalid vote.
Candidate(s) with the most votes:
Alice
Bob
plurality/ $ 


Results for cs50/problems/2026/x/plurality generated by check50 v4.0.0.dev0
:) plurality.c exists
:) plurality compiles
:) vote returns true when given name of first candidate
:) vote returns true when given name of middle candidate
:) vote returns true when given name of last candidate
:) vote returns false when given name of invalid candidate
:) vote produces correct counts when all votes are zero
:) vote produces correct counts after some have already voted
:) vote leaves vote counts unchanged when voting for invalid candidate
:) print_winner identifies Alice as winner of election
:) print_winner identifies Bob as winner of election
:) print_winner identifies Charlie as winner of election
:) print_winner prints multiple winners in case of tie
:) print_winner prints all names when all candidates are tied
*/